# Generated by Django 3.1.3 on 2022-03-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
