# Generated by Django 3.1.3 on 2022-03-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0003_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='clients',
            field=models.IntegerField(default=0),
        ),
    ]
