# Generated by Django 3.1.3 on 2022-03-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0004_activity_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='clients',
            new_name='quantity_of_clients',
        ),
        migrations.AddField(
            model_name='activity',
            name='clients_name',
            field=models.CharField(default='------', max_length=200),
        ),
    ]
