# Generated by Django 3.1.3 on 2022-03-05 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HomeApp', '0005_auto_20220305_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='users',
            field=models.ManyToManyField(related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='clients_name',
            field=models.CharField(default='----', max_length=200),
        ),
    ]
