# Generated by Django 3.1.3 on 2022-03-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0007_auto_20220307_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='clients_name',
        ),
    ]
