# Generated by Django 3.1.3 on 2022-03-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subplan',
        ),
    ]
