# Generated by Django 3.1.3 on 2022-03-03 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0003_activity'),
        ('Users', '0004_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HomeApp.activity'),
        ),
    ]
