# Generated by Django 3.1.3 on 2022-03-03 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0003_activity'),
        ('Users', '0005_user_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.activity'),
        ),
    ]
