# Generated by Django 3.1.3 on 2022-03-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20220303_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activity',
        ),
    ]
